apiVersion: v2
name: pixel-war
description: Pixel War 2026 - jeu collaboratif en temps reel
type: application
version: 1.0.0
appVersion: "1.0.0"

keywords:
  - pixel-war
  - devops

maintainers:
  - name: ISIMA DevOps Team
