# config generale
global:
  imageRegistry: ghcr.io
  imagePullSecrets: []

# frontend
frontend:
  image:
    repository: pixel-war-frontend
    tag:        "latest"
    pullPolicy: Never   # image locale Minikube, pas de pull depuis registry

  replicaCount: 2

  resources:
    requests:
      cpu:    50m
      memory: 64Mi
    limits:
      cpu:    200m
      memory: 128Mi

  service:
    type: ClusterIP
    port: 80

  env:
    VITE_GRID_SIZE: "50"

# backend
backend:
  image:
    repository: pixel-war-backend
    tag:        "latest"
    pullPolicy: Never   # image locale dans minikube

  replicaCount: 2

  resources:
    requests:
      cpu:    100m
      memory: 128Mi
    limits:
      cpu:    500m
      memory: 512Mi

  service:
    type: ClusterIP
    port: 3000

  # references aux ressources creees par terraform
  secretName:    db-credentials
  configMapName: app-config
  dbHost:        postgresql.pixel-war.svc.cluster.local

  hpa:
    enabled:     true
    minReplicas: 2
    maxReplicas: 5
    cpuTarget:   70

  pdb:
    enabled:      true
    minAvailable: 1

# ingress
ingress:
  enabled:          true
  ingressClassName: nginx
  host:             pixel-war.local
  useHostHeader:    true
  tls:              false
  tlsSecretName:    pixel-war-tls

# network policies
networkPolicy:
  enabled: true
